services:
  postgres:
    container_name: ms_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345
      PGDATA: var/lib/postgresql/data
    volumes:
      - postgres: var/lib/postgresql/data
    ports:
      - 5432: 5432
    networks:
      - microservice-net
    restart: unless-stopped

  pgadmin:
    container_name: ms_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 


networks:
  microservice-net:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongo: